### ISSUE TITLE
priklad_16

### ISSUE THREAD

**Issue by KristynaSodomkova** [pesikj/python-012021#3]
Ahoj Jirko, nějak mi nedochází, co myslíš tím "žánr zadej jako parametr funkce." To máme udělat nějakou funkci, která bude obsahovat výběr žánrů? To asi nedam :) Úkol mám myslím hotový, ale nevím, jestli jsem správně splnila zadání... Tohle mi tam prostě hapruje... Moc děkuju za případnou odpověď. K.

**Comment by pesikj** [comment]
Ahoj Kristýno, mělo by to fungovat stejně, jako když jsme pracovali se jménem u zaměstnance a potom u zaměstnance na částečný úvazek. Tj. ve funkci `__init__()` budeš mít žánr jako jeden z parametrů (ideální na to je řetězec) a to pak uložíš pomocí `self` jako atribut objektu. Žádná další složitost tam není :-)

**Comment by KristynaSodomkova** [comment]
Děkuju!
